# Site settings
author: Alain Leukam
title: Why I decided to learn Data Science
header-img: img/home-bg.png
email: leukamal@gmail.com
copyright_name: Alain Leukam
description: > # this means to ignore newlines until "baseurl:"
  The decision
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  leukamal

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
